### ISSUE TITLE
Error: Failed reading config: Invalid db.major_version: 15.

### ISSUE THREAD

**Issue by ssteiger** [supabase/setup-cli#108]
Hey

I'm using the supabase cli with a pg on version 15

config.toml: 

```bash
major_version = 15
```

staging.yml

```bash
name: Supabase - Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.STAGING_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_SUPABASE_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.16.1

      - run: |
          cd packages/app-supabase
          supabase link --project-ref ${{ secrets.STAGING_PROJECT_ID }}
          supabase db push
```

This generates the error: 

```bash
Error: Failed reading config: Invalid db.major_version: 15.
```

When using `major_version = 14` I get the error 

```bash
Error: Remote database Postgres version 15 is incompatible with db.major_version 14. If you are setting up a fresh Supabase CLI project, try changing db.major_version in supabase/config.toml to 15.
```

Any ideas what I could do?

**Comment by sweatybridge** [comment]
Could you try updating cli to latest? This issue should have been fixed a few versions back.

**Comment by ssteiger** [comment]
Yep! Setting `version: 1.27.8` did the trick. Thanks!

For reference:

```yml
name: staging - supabase migration 

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.STAGING_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_SUPABASE_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.27.8

      - run: |
          cd packages/app-supabase
          supabase link --project-ref ${{ secrets.STAGING_PROJECT_ID }}
          supabase db push
```
