### ISSUE TITLE
Using the action with latest CLI fail

### ISSUE THREAD

**Issue by riderx** [supabase/setup-cli#145]
# Bug report
I tried to use the action with this argument and the upload failed all the time.
```
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
           version: 1.42.5
```

## Expected behavior

The upload should work same with the original version and any future one.

## Screenshots

[Link to the action who failed](https://github.com/Cap-go/capgo/actions/runs/4427569438/jobs/7765354992)
