### ISSUE TITLE
getaddrinfo EAI_AGAIN supabase_storage_admin

### ISSUE THREAD

**Issue by KrosnozDanim** [supabase/setup-cli#240]
# Bug report

## Describe the bug
Hello! I'm using supabase with github action, when the command 'supabase start' is launched, I got a crash.
Its might be linked to this issue : https://github.com/supabase/supabase/issues/359, but the start is used on a server.
It's downloading the v0.43.11 and when I go here: https://github.com/supabase/storage/pkgs/container/storage-api it's not the last version, maybe related?

## To Reproduce

- Add this to a Github workflow : 
```
uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase start
```
- Wait for execution
- Get this error : 
```
Status: Downloaded newer image for ghcr.io/supabase/storage-api:v0.43.11
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo EAI_AGAIN supabase_storage_admin
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'supabase_storage_admin'
}
Node.js v18.18.2
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

## System information

- OS: Ubuntu
- Version of supabase-js: always last
- Version of Node.js: 18.18.2

## Additional context

It's been working like 1-2 week ago, not anymore :(
