### ISSUE TITLE
DB Dump - network unreachable

### ISSUE THREAD

**Issue by EricHasegawa** [supabase/setup-cli#266]
- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
- Running actions after `supabase/setup-cli@v1` (tried latest version and several others), dp dump fails with the error
` error: connection to server at "db.<project id>.supabase.co" , port 5432 failed: Network is unreachable
	Is the server running on that host and accepting TCP/IP connections?
	
There's a bunch of people with the same error discussing[ it here](https://www.reddit.com/r/Supabase/comments/1aiu28s/db_dump_network_unreachable/), seems like its fixed in a CLI update but hasn't been updated here.

## To Reproduce
Try something like
`      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Backup roles
        run: supabase db dump --db-url "$supabase_db_url" -f ${{ env.NOW }}/${{ env.NOW }}-roles.sql --role-only
      - name: Backup schema
        run: supabase db dump --db-url "$supabase_db_url" -f ${{ env.NOW }}/${{ env.NOW }}-schema.sql
      - name: Backup data
        run: supabase db dump --db-url "$supabase_db_url" -f ${{ env.NOW }}/${{ env.NOW }}-data.sql --data-only --use-copy

## Expected behavior

Creates backups for me

**Comment by sweatybridge** [comment]
With the new IPv6 rollout, db-url flag won't work on hosts that only support IPv4. You need to link the project before running db dump.

**Comment by EricHasegawa** [comment]
> With the new IPv6 rollout, db-url flag won't work on hosts that only support IPv4. You need to link the project before running db dump.

Could you please link to docs that show how to link the project via github actions? Or point me to anywhere I can learn how to do this?

**Comment by sweatybridge** [comment]
```yaml
env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  # Retrieve <project-id> from dashboard url: https://app.supabase.com/project/<project-id>
  PROJECT_ID: <project-id>

 steps:
   - uses: supabase/setup-cli@v1
     with:
       version: latest
   - run: supabase link --project-ref $PROJECT_ID
   - run: supabase db dump
```

You can find more examples in https://github.com/supabase/supabase-action-example
