### ISSUE TITLE
Unable to access postgres DB when using `setup-cli`- what's the password?

### ISSUE THREAD

**Issue by jason-curtis** [supabase/setup-cli#271]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Can't authenticate against the db that `setup-cli` creates. Can't figure out how to obtain/set the correct password.

## To Reproduce

The following GitHub Action config fails with error `FATAL:  password authentication failed for user "postgres"`.

The action attempts to set up the correct password in 2 ways:
* Using the password listed at https://supabase.com/docs/guides/self-hosting/docker#accessing-postgres (`your-super-secret-and-long-postgres-password`)
* Setting the password in a `.env` file as specified at https://supabase.com/docs/guides/self-hosting/docker#update-secrets .
```yaml
jobs:
  supabase-issue-repro:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
      SUPABASE_CLI_VERSION: 1.148.6
    steps:
      - name: Configure .env for supabase
        run: echo "POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}" >> .env
      - uses: supabase/setup-cli@v1
        with:
          version: ${{ env.SUPABASE_CLI_VERSION }}
      - run: supabase init
      - run: supabase start
      - env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: psql -h localhost -p 54322 -U postgres -c "CREATE DATABASE test;"
```

I've also attempted to connect using prisma, but no luck.

## Expected behavior

I can interact with the DB using prisma or psql

## Screenshots

![image](https://github.com/supabase/setup-cli/assets/3341011/2b7602bf-bbd4-40e5-a2f8-82412ca8200d)

## System information

- `ubuntu-latest` GitHub actions runner.
- tried with supabase CLI version `1.148.6` and `1.136.3` (version mentioned in README.md)
