### ISSUE TITLE
No response from `supabase_storage` container 

### ISSUE THREAD

**Issue by rpie3** [supabase/setup-cli#296]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using `latest`, I receive the following message while running an action which calls `supabase db reset`:
`failed to inspect container health: Error response from daemon: No such container: supabase_storage_repo-name`

When explictly setting an earlier version, the issue is resolved. I have adjusted from 
```yaml
  - uses: supabase/setup-cli@v1
    with:
      version: latest
```          
to
```yaml
  - uses: supabase/setup-cli@v1
    with:
      version: 1.187.3
```    
to get my actions running successfully again.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Run the action:
```yaml
on:
  pull_request:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase db stop
      - run: supabase db start
      - run: supabase db reset
```      

## Expected behavior

`latest` should be functional for seeding Supabase.

## System information

- GitHub Action, using runs-on `ubuntu-latest`
