### ISSUE TITLE
Cannot run test with extension pgmq

### ISSUE THREAD

**Issue by riderx** [supabase/setup-cli#315]
# Bug report

I added pgmq in my stack and want to run E2E test before release, but it fail because it cannot find the extension:
https://github.com/Cap-go/capgo/actions/runs/12269514192/job/34233209931

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Add in a migration file:
CREATE EXTENSION IF NOT EXISTS "pgmq";
then try to start Supabase in CI

## Expected behavior

It shouldn't fail

**Comment by sweatybridge** [comment]
The next stable release of cli will include the postgres image with pgmq. Meanwhile, you can pin the beta version of cli in your github action.

```
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.0.8
```
