### ISSUE TITLE
v1.136.3 installed by default

### ISSUE THREAD

**Issue by groksrc** [supabase/setup-cli#323]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The day before yesterday I started receiving the following error on my CI pipeline that had been working correctly for months:
```
Run supabase link --project-ref $SUPABASE_PROJECT_ID
failed to connect to postgres: failed to connect to `host=db.<redacted>.supabase.co user=postgres database=postgres`: dial error (dial tcp [<redacted ip6 address>]:5432 connect: network is unreachable)
Try rerunning the command with --debug to troubleshoot the error.
```

After some investigation it was determined that the version of the CLI being installed by supabase/setup-cli by default is v1.136.3.

This version no longer works in GitHub actions. 

## To Reproduce

Create a CI pipeline that looks like this:

```
name: CI/CD Workflow

on:
  push:
    branches:
      - main

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

     - uses: supabase/setup-cli@v1
     - run: supabase --version
     - run: supabase link --project-ref $SUPABASE_PROJECT_ID
     - run: supabase db push
     - run: supabase functions deploy
```

## Expected behavior

The command `supabase link` does not fail by default.

## Screenshots

<img width="1544" alt="Image" src="https://github.com/user-attachments/assets/f84d40ec-20a1-47d1-8acf-4e2f94ea80f2" />

## System information

`ubuntu-latest` per the yaml file

## Additional context

This is fixed by specifying a more recent CLI version:

```
      - uses: supabase/setup-cli@v1
        with:
          version: latest
```
