### ISSUE TITLE
Github action // Error: error running container

### ISSUE THREAD

**Issue by alex-galey** [supabase/setup-cli#51]
# Bug report

## Describe the bug

Hi @sweatybridge,

I'm trying to create [an action to generate automatically db types](https://github.com/alex-galey/generate-supabase-db-types-github-action/tree/supabase-cli) and based my dev [on this project](https://github.com/lyqht/generate-supabase-db-types-github-action/issues/8)

I can't get more than `Error: error running container `

Here's what I'm using : 
```
    - name: "Generate database typescript types"
      shell: bash
      env:
        SUPABASE_REF_ID: ${{ inputs.SUPABASE_REF_ID }}
        SUPABASE_ACCESS_TOKEN: ${{ inputs.SUPABASE_ACCESS_TOKEN }}
        DB_PASSWORD: ${{ inputs.DB_PASSWORD }}
        OUTPUT_PATH: ${{ inputs.OUTPUT_PATH }}
      run: |
        supabase link --project-ref ${SUPABASE_REF_ID} --password ${DB_PASSWORD}
        supabase gen types typescript --db-url 'postgresql://postgres:${DB_PASSWORD}@db.${SUPABASE_REF_ID}.supabase.co:5432/postgres' > ${OUTPUT_PATH}
```

Can you help about it ?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Use it as an action :
```
    steps:
      - uses: alex-galey/generate-supabase-db-types-github-action@supabase-cli
        with:
            SUPABASE_REF_ID: ${{ secrets.SUPABASE_REF_ID }}
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            OUTPUT_PATH: db.types.ts
```

## Expected behavior

The Github action generates db.types.ts

## System information

- OS: ubuntu-latest from Github action
- Version of supabase-js: 1.4.6
